### ISSUE TITLE
Graph Display

### ISSUE THREAD

**Issue by Farmer-Pete** [Misfit-Ninjas/brainwave-ninja#3]
## Big Picture

The problem that we're trying to solve in Brainwave v4 is this: **Can we implement the two algorithms we created in v3 as a graph-based interface?**

See the [overall design](https://github.com/Misfit-Ninjas/brainwave-next/assets/265612/124939ea-c045-40a6-a096-b0806e02b1f3) for a refresher, but note that what we're developing in this scope is, well, scoped much smaller

## How Might We?

**How might we add a graph display so that our users who can easily see how data flows between neurons?**

### Sequence Diagram

```mermaid
sequenceDiagram
    box Javascript
        participant ReactFlow
        participant JS as Initial page view
    end
    box Python
        participant Django as Django View
        participant Brain
        participant Neurons
    end
    JS->>+Django: Fetch Neurons
    note over JS, Django: Communication should use REST<br/>GET /api/brain/<ID>
    Django->>+Brain: Get neurons
    Brain->>+Neurons: Get neuron name
    Brain->>+Django: List of neuron names <br/> and connections
    Django->>+JS: JSON Response
    JS->>+ReactFlow: Render connected nodes
```

### Class Diagram

```mermaid
classDiagram
    PEExplorer <-- Brain
    CompanyShapeAnalysis <-- Brain
    Brain <-- Neuron

    class CompanyShapeAnalysis {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame] // OOS!
    }

    class PEExplorer {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame] // OOS!
    }
 
    class Brain {
        neurons: Dict[uuid4,Neuron]
        synapses: Dict[uuid4,uuid4]
        add_neuron(Neuron) -> uuid4
        get_neuron(id: uuid4) -> Neuron // OOS!
        add_synapse(uuid4, uuid4) -> None
        export() -> Dict
        execute(payload: dict) -> Dict // OOS!
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame] // OOS!
    }

    class Neuron {
        ConfigClass: NeuronConfig // OOS!
        name: Str
        display_mode: DisplayModeEnum
        export() -> Dict
        run(config: NeuronConfig, **kwargs) -> Dict // OOS!
    }

	class DisplayModeEnum {
		NAME_ONLY
		NAME_PLUS_GRAPH
		NAME_PLUS_GRID
	}

    DisplayModeEnum <-- Neuron
    Neuron <-- GlobalConfig
    Neuron <-- MachineLearning
    Neuron <-- FutureQuarters
    Neuron <-- Sector
    Neuron <-- Quarters
    Neuron <-- Profile
    Neuron <-- Symbols
    Neuron <-- NetIncome
    Neuron <-- DilutedShares
    Neuron <-- TTMNetDistributedEPS
    Neuron <-- StockPrice
    Neuron <-- PERatio
```

> [!NOTE]
> Things labled `OOS!` are "out of scope" as they are being implemented in other scope tickets. This is just so you can see how the pieces fit together

#### `DisplayModeEnum`

| Value | Meaning |
|-------|---------|
| `NAME_ONLY` | The neuron should only display its name |
| `NAME_PLUS_GRAPH` | The neuron should display its name and also a graph |
| `NAME_PLUS_GRID` | The neuron should display its name and also a grid |

Refer to the [overall design](https://github.com/Misfit-Ninjas/brainwave-next/assets/265612/124939ea-c045-40a6-a096-b0806e02b1f3) to see how each node will be rendered

### REST+JSON Response

```js
{
  "neurons": [
  	{
	  "id": "d0032913-b01e-4641-9ce2-43368958c49c", // UUID4
	  "name": "Sector", // String
	  "display": "NODE",
  	}, {
      "id": "b6aab59d-9387-4fa1-99f7-be8a2dd36d22",
	  "name": "Quarters",
	  "display: "NODE",
  	}, {
	  // ...
	}
  ],
  "synapses": {
	"d0032913-b01e-4641-9ce2-43368958c49c": "b6aab59d-9387-4fa1-99f7-be8a2dd36d22",
	// ...
  }
}
```

## Tasks

> [!NOTE]
> These are _not_ listed in the order that they should be implemented

> [!TIP]
> Create an issue/ticket from a task that you want to work on ([instructions if you need them](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-task-list-item)) so you can assign the work to yourself. However, keep any communication either in the discussion threads or as comments in the scope tickets. Communicationg through tickets silohs ourselves and makes cross-team more difficult. None of these this can be built in insolation and you'll need to coordinate with each other.

**Frontend Tasks**
* [ ] Create REST request to Django
* [ ] Convert REST request into a format that ReactFlow can understand
* [ ] #22
* [ ] Render `NAME_PLUS_GRAPH` nodes in ReactFlow
* [ ] Render `NAME_PLUS_GRID` nodes in ReactFlow

**Backend Tasks**
* [ ] Create `/brain` view to handle request and return JSON response
* [ ] Create `CompanyShapeAnalysis` and `PEExplorer` brains
* [ ] Create Neurons (listed in the class diagram)
