### ISSUE TITLE
Node configuration

### ISSUE THREAD

**Issue by Farmer-Pete** [Misfit-Ninjas/brainwave-ninja#4]
## Big Picture

The problem that we're trying to solve in Brainwave v4 is this:

> **Can we implement the two algorithms we created in v3 as a graph-based interface?**

See the [overall design](https://github.com/Misfit-Ninjas/brainwave-next/assets/265612/124939ea-c045-40a6-a096-b0806e02b1f3) for a refresher, but note that what we're developing in this scope is, well, scoped much smaller

## How Might We?

**How might we add the ability to edit nodes so that our users can easily change the configuration for each node?**

### Sequence Diagram

```mermaid
sequenceDiagram
    actor User
    box Javascript
        participant ReactFlow
        participant React
    end
    box Python
        participant Django as Django View
        participant Brain
        participant Neuron
    end
   
    User->>+ReactFlow: Clicks on node
    ReactFlow->>+React: Trigger node clicked event
    React->>+Django: Get JSON schema
    note over React,Django: Communication should use REST<br/>GET /api/brain/neuron/<UUID4>
    Django->>+Brain: Get Neuron object
    Brain->>+Django: Neuron object
    Django->>+Neuron: Get JSON schema
    Neuron->>+Django: JSON schema
    Django->>+Neuron: Get form values
    Neuron->>+Django: Form values
    Django->>+React: JSON schema plus<br/> form values response
    React->>+User: HTML Form

    User->>+React: Makes form modification
    React->>+Django: Sends form data
    note over React,Django: PUT /api/brain/neuron/<UUID4>
    Django->>+Brain: Get Neuron object
    Brain->>+Django: Neuron object
    Django->>+Neuron: Send form values
    Neuron->>+Django: New form values
    Django->>+React: New form values
    React->>+User: Update HTML form
```

> [!TIP]
> The reason that the form modification request returns "New form values" is to allow for nodes where updating one field may impact other fields. For example, when selecting a country, for example, it should change the stock markets available.

> [!WARNING]
> We are accepting the following (big) limitation: It won't update any of the nodes' output. The user will have to click the "Execute" button to see their change applied. Furthermore, any "New form values" calculations will have to be done without executing the nodes. This is a big limitation and will for sure cause confusion to our users. However, for the sake of simplifying the design, we're accepting this limitation for now. We'll fix this later in a future release.

### Class Diagram

```mermaid
classDiagram

    CompanyShapeAnalysis --> Brain
    PEExplorer --> Brain
    Brain <-- Neuron

    class CompanyShapeAnalysis {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame] // OOS!
    }

    class PEExplorer {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame] // OOS!
    }
 
    class Brain{
        neurons: Dict[uuid4,Neuron]
        synapses: Dict[uuid4,uuid4] // OOS!
        add_neuron(Neuron) -> uuid4 // OOS!
        get_neuron(id: uuid4) -> Neuron
        add_synapse(uuid4, uuid4) -> None // OOS!
        export() -> Dict // OOS!
        execute(payload: dict) -> Dict
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame] // OOS!
    }

    class Neuron {
        ConfigClass: NeuronConfig
        name: Str // OOS!
        display_mode: DisplayModeEnum // OOS!
        export() -> Dict // OOS!
        run(config: NeuronConfig, **kwargs) -> Dict // OOS!
    }

    class NeuronConfig {
        @classmethod new(**kwargs) -> NeuronConfig
        get_schema() -> Dict // See pydantic.model_json_schema()
        get_values() -> Dict // See pydantic.model_dump()
    }

    pydantic <-- NeuronConfig
    Neuron --> NeuronConfig
    NeuronConfig <-- SectorConfig
    NeuronConfig <-- QuartersConfig
    NeuronConfig <-- ProfileConfig
    NeuronConfig <-- SymbolsConfig
    NeuronConfig <-- NetIncomeConfig
    NeuronConfig <-- DilutedSharesConfig
    NeuronConfig <-- TTMNetDistributedEPSConfig
    NeuronConfig <-- StockPriceConfig
    NeuronConfig <-- PERatioConfig
```

> [!NOTE]
> Things labled `OOS!` are "out of scope" as they are being implemented in other scope tickets. This is just so you can see how the pieces fit together

## Tasks

> [!NOTE]
> These are _not_ listed in the order that they should be implemented

> [!TIP]
> Create an issue/ticket from a task that you want to work on ([instructions if you need them](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-task-list-item)) so you can assign the work to yourself. However, keep any communication either in the discussion threads or as comments in the scope tickets. Communicationg through tickets silohs ourselves and makes cross-team more difficult. None of these this can be built in insolation and you'll need to coordinate with each other.

**Frontend Tasks**
* [ ] Add a sidebar to hold node configuration
* [ ] Configure ReactFlow so that when a node is clicked, the sidebar is updated by a function
* [ ] Create a function that reads a JSON schema and displays a form.
* [ ] Enhance the function to do a REST request

**Backend Tasks**
* [ ] Create `/neuron/<UUID4>` view to handle request and return JSON response
* [ ] Create NeuronConfig class to handle config creation and serialization
* [ ] Create neuron configurations (listed in the class diagram)

## Resources
* https://docs.pydantic.dev/latest/
* https://docs.pydantic.dev/latest/concepts/json_schema/
* https://docs.pydantic.dev/latest/concepts/serialization/
* https://jsonforms.io/docs/integrations/react/
