### ISSUE TITLE
Node execution

### ISSUE THREAD

**Issue by Farmer-Pete** [Misfit-Ninjas/brainwave-ninja#5]
## Big Picture

The problem that we're trying to solve in Brainwave v4 is this:

> **Can we implement the two algorithms we created in v3 as a graph-based interface?**

See the [overall design](https://github.com/Misfit-Ninjas/brainwave-next/assets/265612/124939ea-c045-40a6-a096-b0806e02b1f3) for a refresher, but note that what we're developing in this scope is, well, scoped much smaller

## How Might We?

**How might we add the ability to execute the brain so that our users can see the results?**

### Sequence Diagram

```mermaid
sequenceDiagram
    actor User
    box Javascript
        participant UI
        participant React
    end
    box Python
        participant Django as Django View
        participant Brain
        participant Neuron
        participant Cache
    end
   
    User->>+UI: Clicks on EXECUTE button
    UI->>+React: Trigger button clicked event
    React->>+Django: Run brain's neurons
    note over React,Django: Communication should use REST<br/>GET /api/brain/<ID>/results
    Django->>+Brain: Run brain
    loop every neuron
        Brain->>+Neuron: Run neuron
        Neuron->>Cache: Set/get/update API cache
        Cache->>Neuron: Cached results
        Neuron->>+Brain: Reults
    end
    Brain->>+Django: Results by neuron
    Django->>+React: JSON results by neuron
    React->>+UI: Update node displays
```

> [!TIP]
> We _could_ make the brain's method smarter by allowing it to discover the execution order by leveraging the neurons + synapses. However, since we're not allowing for any neurons to be added or removed, there's little benefit in doing that. So we'll just hard-code the execution order for each brain.

> [!TIP]
> We already have some great caching logic in Brainwave v3, so let's just use that

### Class Diagram

```mermaid
classDiagram
    PEExplorer <-- Brain
    CompanyShapeAnalysis <-- Brain
    Brain <-- Neuron

    class CompanyShapeAnalysis {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame]
    }

    class PEExplorer {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame]
    }
 
    class Brain {
        run(payload: Dict[uuid4, NeuronConfig]) -> Dict[uuid4, DataFrame]
        neurons: Dict[uuid4,Neuron] // OOS!
        synapses: Dict[uuid4,uuid4] // OOS!
        add_neuron(Neuron) -> uuid4 // OOS!
        get_neuron(id: uuid4) -> Neuron // OOS!
        add_synapse(uuid4, uuid4) -> None // OOS!
        export() -> Dict // OOS!
    }

    class Neuron {
        run(config: NeuronConfig, **kwargs) -> Dict
        ConfigClass: NeuronConfig // OOS!
        name: Str // OOS!
        display_mode: DisplayModeEnum // OOS!
        export() -> Dict // OOS!
    }

    Neuron <-- GlobalConfig
    Neuron <-- MachineLearning
    Neuron <-- FutureQuarters
    Neuron <-- Sector
    Neuron <-- Quarters
    Neuron <-- Profile
    Neuron <-- Symbols
    Neuron <-- NetIncome
    Neuron <-- DilutedShares
    Neuron <-- TTMNetDistributedEPS
    Neuron <-- StockPrice
    Neuron <-- PERatio
```

> [!NOTE]
> Things labled `OOS!` are "out of scope" as they are being implemented in other scope tickets. This is just so you can see how the pieces fit together

### `run()` function signatures of all the `Neuron` classes

| Class | `run(...)` function signature |
|-------|-------------------------------|
| `GlobalConfig` | `run(config: NeuronConfig) -> DataFrame` |
| `MachineLearning` | `run(config: NeuronConfig) -> DataFrame` |
| `FutureQuarters` | `run(config: NeuronConfig) -> DataFrame` |
| `Sector` | `run(config: NeuronConfig) -> DataFrame` |
| `Quarters` | `run(config: NeuronConfig, sector_result: DataFrame) -> DataFrame` |
| `Profile` | `run(config: NeuronConfig, sector_result: DataFrame, quarters_result: DataFrame) -> DataFrame` |
| `SymbolsResult` | `run(config: NeuronConfig, profile_result: DataFrame) -> DataFrame` |
| `Symbols` | `run(config: NeuronConfig) -> DataFrame` |
| `Quarters` | `run(config: NeuronConfig, symbols_result: DataFrame) -> DataFrame` |
| `NetIncome` | `run(config: NeuronConfig, symbols_result: DataFrame, quarters_result: DataFrame) -> DataFrame` |
| `DilutedShares` | `run(config: NeuronConfig, symbols_result: DataFrame, quarters_result: DataFrame) -> DataFrame` |
| `TTMNetDistributedEPS` | `run(config: NeuronConfig, net_income_result: DataFrame, diluted_shares_result: DataFrame) -> DataFrame` |
| `StockPrice` | `run(config: NeuronConfig, ttm_net_distrubted_eps_result: DataFrame) -> DataFrame`|
| `PE Ratio` | `run(config: NeuronConfig, stock_price_result: DataFrame) -> DataFrame` |

## Tasks

> [!NOTE]
> These are _not_ listed in the order that they should be implemented

> [!TIP]
> Create an issue/ticket from a task that you want to work on ([instructions if you need them](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-task-list-item)) so you can assign the work to yourself. However, keep any communication either in the discussion threads or as comments in the scope tickets. Communicationg through tickets silohs ourselves and makes cross-team more difficult. None of these this can be built in insolation and you'll need to coordinate with each other.

**Frontend Tasks**
* [ ] Add a "Run" button 
* [ ] Create a function that takes a payload and then updates the nodes' displayed data
* [ ] Enhance the function to do a REST request

**Backend Tasks**
* [ ] #6
* Enhance Neuron classes to have a `run(...)` method
    * [ ] `GlobalConfig` #9
    * [ ] `MachineLearning` #9
    * [ ] `FutureQuarters` #9
    * [ ] #13
    * [ ] #16
    * [ ] #18
    * [ ] `SymbolsResult`
    * [ ] #15
    * [ ] `NetIncome`
    * [ ] #21
    * [ ] `TTMNetDistributedEPS`
    * [ ] `StockPrice`
    * [ ] `PERatio`
* [ ] #20
* [ ] Add `run(...)` methods to the `PEExplorer` brains
